# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jbell/repos/Sandbox/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jbell/repos/Sandbox/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbell/repos/Sandbox/cpp/CMakeFiles /home/jbell/repos/Sandbox/cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbell/repos/Sandbox/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sowhat

# Build rule for target.
sowhat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sowhat
.PHONY : sowhat

# fast build rule for target.
sowhat/fast:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/build
.PHONY : sowhat/fast

card.o: card.cpp.o

.PHONY : card.o

# target to build an object file
card.cpp.o:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card.cpp.o
.PHONY : card.cpp.o

card.i: card.cpp.i

.PHONY : card.i

# target to preprocess a source file
card.cpp.i:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card.cpp.i
.PHONY : card.cpp.i

card.s: card.cpp.s

.PHONY : card.s

# target to generate assembly for a file
card.cpp.s:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card.cpp.s
.PHONY : card.cpp.s

card_deck.o: card_deck.cpp.o

.PHONY : card_deck.o

# target to build an object file
card_deck.cpp.o:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_deck.cpp.o
.PHONY : card_deck.cpp.o

card_deck.i: card_deck.cpp.i

.PHONY : card_deck.i

# target to preprocess a source file
card_deck.cpp.i:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_deck.cpp.i
.PHONY : card_deck.cpp.i

card_deck.s: card_deck.cpp.s

.PHONY : card_deck.s

# target to generate assembly for a file
card_deck.cpp.s:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_deck.cpp.s
.PHONY : card_deck.cpp.s

card_game_war.o: card_game_war.cpp.o

.PHONY : card_game_war.o

# target to build an object file
card_game_war.cpp.o:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_game_war.cpp.o
.PHONY : card_game_war.cpp.o

card_game_war.i: card_game_war.cpp.i

.PHONY : card_game_war.i

# target to preprocess a source file
card_game_war.cpp.i:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_game_war.cpp.i
.PHONY : card_game_war.cpp.i

card_game_war.s: card_game_war.cpp.s

.PHONY : card_game_war.s

# target to generate assembly for a file
card_game_war.cpp.s:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_game_war.cpp.s
.PHONY : card_game_war.cpp.s

card_hand.o: card_hand.cpp.o

.PHONY : card_hand.o

# target to build an object file
card_hand.cpp.o:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_hand.cpp.o
.PHONY : card_hand.cpp.o

card_hand.i: card_hand.cpp.i

.PHONY : card_hand.i

# target to preprocess a source file
card_hand.cpp.i:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_hand.cpp.i
.PHONY : card_hand.cpp.i

card_hand.s: card_hand.cpp.s

.PHONY : card_hand.s

# target to generate assembly for a file
card_hand.cpp.s:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_hand.cpp.s
.PHONY : card_hand.cpp.s

card_player.o: card_player.cpp.o

.PHONY : card_player.o

# target to build an object file
card_player.cpp.o:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_player.cpp.o
.PHONY : card_player.cpp.o

card_player.i: card_player.cpp.i

.PHONY : card_player.i

# target to preprocess a source file
card_player.cpp.i:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_player.cpp.i
.PHONY : card_player.cpp.i

card_player.s: card_player.cpp.s

.PHONY : card_player.s

# target to generate assembly for a file
card_player.cpp.s:
	$(MAKE) -f CMakeFiles/sowhat.dir/build.make CMakeFiles/sowhat.dir/card_player.cpp.s
.PHONY : card_player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sowhat"
	@echo "... card.o"
	@echo "... card.i"
	@echo "... card.s"
	@echo "... card_deck.o"
	@echo "... card_deck.i"
	@echo "... card_deck.s"
	@echo "... card_game_war.o"
	@echo "... card_game_war.i"
	@echo "... card_game_war.s"
	@echo "... card_hand.o"
	@echo "... card_hand.i"
	@echo "... card_hand.s"
	@echo "... card_player.o"
	@echo "... card_player.i"
	@echo "... card_player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

